artifacts_root: artifacts
data_ingest:
  root_dir: artifacts/data_ingest
  source_URL: https://raw.githubusercontent.com/mlflow/mlflow-example/refs/heads/master/wine-quality.csv
  local_data_file: artifacts/data_ingest/data.csv
  unzip_dir: artifacts/data_ingest

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingest/data.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingest/data.csv